name: WebGL Build and Deploy

on: workflow_dispatch

jobs:
  build:
    name: Build for WebGL
    runs-on: ubuntu-latest
    steps:
      # Clean up
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
      # Cache
      - uses: actions/cache@v3
        with:
          path: ./Library
          key: Library-${{ hashFiles('./Assets/**', './Packages/**', './ProjectSettings/**') }}
          restore-keys: |
            Library-
      # Build
      - name: Build WebGL project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          projectPath: ./
          unityVersion: 2023.2.5f1
          allowDirtyBuild: true
          buildName: LatestBuild
      # Output
      - name: Upload build to artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: WebGLBuild
          path: ./build/WebGL/LatestBuild

  #Deploy webGL build
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      #Download build
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: WebGLBuild
          path: ./build/WebGL/LatestBuild
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/WebGL/LatestBuild
          publish_branch: webGL
